# Generated by Django 5.1.6 on 2025-04-27 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allservices', '0002_servicecategory_remove_electricalservicebooking_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='subservice',
            name='category',
        ),
        migrations.AlterModelOptions(
            name='servicebooking',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='servicebooking',
            name='status',
        ),
        migrations.RemoveField(
            model_name='subservice',
            name='base_price',
        ),
        migrations.AddField(
            model_name='subservice',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='allservices.subservice'),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='subservice',
            name='service',
            field=models.ForeignKey(default=0.0, on_delete=django.db.models.deletion.CASCADE, related_name='subservices', to='allservices.service'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ServiceCategory',
        ),
    ]
