# Generated by Django 5.1.6 on 2025-04-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allservices', '0003_service_remove_subservice_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subservice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
