# Generated by Django 5.1.6 on 2025-04-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allservices', '0003_service_remove_subservice_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subservice',
            name='service',
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='service',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelOptions(
            name='servicebooking',
            options={},
        ),
        migrations.RemoveField(
            model_name='servicebooking',
            name='additional_notes',
        ),
        migrations.RemoveField(
            model_name='servicebooking',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='SubService',
        ),
    ]
