# Generated by Django 5.1.6 on 2025-04-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allservices', '0004_remove_subservice_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebooking',
            name='address',
            field=models.CharField(max_length=255),
        ),
    ]
