# Generated by Django 5.1.6 on 2025-04-27 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allservices', '0004_alter_subservice_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={},
        ),
        migrations.AlterModelOptions(
            name='servicebooking',
            options={},
        ),
        migrations.RemoveField(
            model_name='service',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='servicebooking',
            name='additional_notes',
        ),
        migrations.RemoveField(
            model_name='servicebooking',
            name='created_at',
        ),
    ]
