# Generated by Django 5.1.6 on 2025-05-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allservices', '0005_alter_servicebooking_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
