# Generated by Django 5.1.6 on 2025-04-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allservices', '0005_alter_service_options_alter_servicebooking_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subservice',
            name='service',
        ),
        migrations.RemoveField(
            model_name='servicebooking',
            name='service',
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='service_type',
            field=models.CharField(default=0.0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='SubService',
        ),
    ]
