# Generated by Django 5.1.6 on 2025-05-09 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allservices', '0006_servicebooking_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 5, 9, 10, 42, 52, 951404, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='service',
            field=models.CharField(choices=[('cleaning', 'Cleaning'), ('painting', 'Painting'), ('roofing', 'Roofing'), ('electrical', 'Electrical'), ('flooring', 'Flooring'), ('plastering', 'Plastering'), ('plumbing', 'Plumbing'), ('appliance', 'Appliance')], max_length=100),
        ),
    ]
