# Generated by Django 5.1.6 on 2025-04-27 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allservices', '0006_remove_subservice_service_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicebooking',
            old_name='service_type',
            new_name='service',
        ),
    ]
