# Generated by Django 5.1.6 on 2025-05-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allservices', '0007_servicebooking_created_at_servicebooking_revenue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('age', models.PositiveIntegerField()),
                ('service_type', models.CharField(choices=[('cleaning', 'Cleaning'), ('painting', 'Painting'), ('roofing', 'Roofing'), ('electrical', 'Electrical'), ('flooring', 'Flooring'), ('plastering', 'Plastering'), ('plumbing', 'Plumbing'), ('appliance', 'Appliance')], max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='provider_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
